DROP DATABASE journal;
CREATE DATABASE journal;

USE journal;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(20),
  lastName VARCHAR(20),
  email VARCHAR(30) UNIQUE,
  username VARCHAR(20) UNIQUE,
  password VARCHAR(20)
);